import React from "react";
import LegalPage from "@/components/legal/LegalPage";

const SECTIONS = [
  {
    heading: "Accepting these terms",
    body: [
      "DEVLAUNCH is a free student platform for discovering AI tools, learning, practising code and building projects with a team. By creating an account or using the platform you agree to these terms and to the Privacy Policy.",
    ],
  },
  {
    heading: "Who can use it",
    body: [
      "DEVLAUNCH is intended for college-age engineering students. You need a valid email address to register, and you are responsible for what happens through your account. If you are under 18, use the platform with the knowledge and consent of a parent or guardian.",
    ],
  },
  {
    heading: "Your account",
    bullets: [
      "Keep your password private and do not share your account — the verification codes we send are for you alone.",
      "Give accurate details, especially the email and mobile number you verify.",
      "If you believe someone else has access to your account, change your password immediately and contact us.",
    ],
  },
  {
    heading: "Acceptable use",
    body: ["Use DEVLAUNCH to learn and build. Do not:"],
    bullets: [
      "break the law, or upload anything illegal, hateful, harmful or designed to damage someone else's device;",
      "abuse the AI features, attempt to bypass rate limits or usage limits, or automate requests to overload the platform;",
      "scrape, copy or resell the platform's content in bulk, or attempt to access other students' accounts or data;",
      "submit AI-generated work as your own where your college, course or event rules forbid it — you are responsible for following your institution's academic integrity rules;",
      "impersonate another person or a team you do not represent.",
    ],
  },
  {
    heading: "Your content",
    body: [
      "You own the work you create: your project ideas, code, answers, tasks and comments stay yours. By saving it on DEVLAUNCH you give us permission to store, process and display it so that the features you used work — for example showing a solution review back to you, or a task to your team.",
      "You are responsible for what you upload. Do not upload someone else's work without permission.",
    ],
  },
  {
    heading: "AI features",
    body: [
      "The AI Mentor, Project Roadmap Generator, code review and tool suggestions are generated by third-party AI models. They can be inaccurate, out of date or incomplete, and they are study aids rather than professional advice. Always check important output yourself before relying on it, and never paste secrets, passwords or private data into an AI feature.",
    ],
  },
  {
    heading: "Tools and links we list",
    body: [
      "The AI Tools directory describes third-party products and links to their websites. We verify listings and pricing dates where we can, but features and prices change and are controlled by those providers, not by us. Your use of any third-party tool is governed by that provider's own terms.",
    ],
  },
  {
    heading: "XP, badges and leaderboards",
    body: [
      "Progress, XP, coins, streaks, badges and leaderboard positions are motivational features, not academic credentials. We may adjust or reset them if they are gained by automating or abusing the platform.",
    ],
  },
  {
    heading: "Availability and changes",
    body: [
      "DEVLAUNCH is provided as-is and free of charge. We may add, change, pause or remove features at any time, and we may update these terms — the date at the top will change when we do. We aim to keep content accurate, but we do not promise uninterrupted availability.",
    ],
  },
  {
    heading: "Ending access",
    body: [
      "You can stop using DEVLAUNCH at any time and delete your account from Profile → Delete account. We may suspend or remove an account that breaks these terms, abuses other students, or threatens the security of the platform.",
    ],
  },
  {
    heading: "Liability",
    body: [
      "To the extent permitted by law, DEVLAUNCH and MrunalTech are not liable for indirect or consequential losses arising from your use of the platform, including decisions made in reliance on AI-generated content or third-party tool listings. Nothing here limits rights you have under applicable law.",
    ],
  },
  {
    heading: "Governing law and contact",
    body: [
      "These terms are governed by the laws of India. Questions, reports or complaints can be raised through the Contact page or by writing to mrunaltech9@gmail.com.",
    ],
  },
];

export default function Terms() {
  return (
    <LegalPage
      title="Terms of Use"
      updated="4 October 2026"
      metaDescription="The rules for using DEVLAUNCH: your account, acceptable use, your content, AI features and liability."
      intro="These terms explain what you can expect from DEVLAUNCH and what we expect from you. Plain language on purpose — the short version is: learn, build, be honest, and do not misuse the platform or other students."
      sections={SECTIONS}
    />
  );
}